//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BridgeMail", "GroupMail_GroupsGoupMail_Person", "GroupMail_Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.BridgeMail.Data.GroupMail_Groups), "GoupMail_Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.BridgeMail.Data.GoupMail_Person))]
[assembly: EdmRelationshipAttribute("BridgeMail", "GroupMail_GroupsGroupMail_History", "GroupMail_Groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gooddogs.Modules.Dnn.BridgeMail.Data.GroupMail_Groups), "GroupMail_History", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gooddogs.Modules.Dnn.BridgeMail.Data.GroupMail_History), true)]

#endregion

namespace Gooddogs.Modules.Dnn.BridgeMail.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BridgeMailContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BridgeMailContainer object using the connection string found in the 'BridgeMailContainer' section of the application configuration file.
        /// </summary>
        public BridgeMailContainer() : base("name=BridgeMailContainer", "BridgeMailContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BridgeMailContainer object.
        /// </summary>
        public BridgeMailContainer(string connectionString) : base(connectionString, "BridgeMailContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BridgeMailContainer object.
        /// </summary>
        public BridgeMailContainer(EntityConnection connection) : base(connection, "BridgeMailContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GoupMail_Person> GoupMail_Person
        {
            get
            {
                if ((_GoupMail_Person == null))
                {
                    _GoupMail_Person = base.CreateObjectSet<GoupMail_Person>("GoupMail_Person");
                }
                return _GoupMail_Person;
            }
        }
        private ObjectSet<GoupMail_Person> _GoupMail_Person;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GroupMail_Groups> GroupMail_Groups
        {
            get
            {
                if ((_GroupMail_Groups == null))
                {
                    _GroupMail_Groups = base.CreateObjectSet<GroupMail_Groups>("GroupMail_Groups");
                }
                return _GroupMail_Groups;
            }
        }
        private ObjectSet<GroupMail_Groups> _GroupMail_Groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<GroupMail_History> GroupMail_History
        {
            get
            {
                if ((_GroupMail_History == null))
                {
                    _GroupMail_History = base.CreateObjectSet<GroupMail_History>("GroupMail_History");
                }
                return _GroupMail_History;
            }
        }
        private ObjectSet<GroupMail_History> _GroupMail_History;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GoupMail_Person EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGoupMail_Person(GoupMail_Person goupMail_Person)
        {
            base.AddObject("GoupMail_Person", goupMail_Person);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupMail_Groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupMail_Groups(GroupMail_Groups groupMail_Groups)
        {
            base.AddObject("GroupMail_Groups", groupMail_Groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the GroupMail_History EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToGroupMail_History(GroupMail_History groupMail_History)
        {
            base.AddObject("GroupMail_History", groupMail_History);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BridgeMail", Name="GoupMail_Person")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GoupMail_Person : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GoupMail_Person object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdByUser">Initial value of the CreatedByUser property.</param>
        public static GoupMail_Person CreateGoupMail_Person(global::System.Int32 itemID, global::System.Int32 moduleID, global::System.DateTime createdDate, global::System.Int32 createdByUser)
        {
            GoupMail_Person goupMail_Person = new GoupMail_Person();
            goupMail_Person.ItemID = itemID;
            goupMail_Person.ModuleID = moduleID;
            goupMail_Person.CreatedDate = createdDate;
            goupMail_Person.CreatedByUser = createdByUser;
            return goupMail_Person;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedByUser
        {
            get
            {
                return _CreatedByUser;
            }
            set
            {
                OnCreatedByUserChanging(value);
                ReportPropertyChanging("CreatedByUser");
                _CreatedByUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByUser");
                OnCreatedByUserChanged();
            }
        }
        private global::System.Int32 _CreatedByUser;
        partial void OnCreatedByUserChanging(global::System.Int32 value);
        partial void OnCreatedByUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMail
        {
            get
            {
                return _EMail;
            }
            set
            {
                OnEMailChanging(value);
                ReportPropertyChanging("EMail");
                _EMail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMail");
                OnEMailChanged();
            }
        }
        private global::System.String _EMail;
        partial void OnEMailChanging(global::System.String value);
        partial void OnEMailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CellPhone
        {
            get
            {
                return _CellPhone;
            }
            set
            {
                OnCellPhoneChanging(value);
                ReportPropertyChanging("CellPhone");
                _CellPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CellPhone");
                OnCellPhoneChanged();
            }
        }
        private global::System.String _CellPhone;
        partial void OnCellPhoneChanging(global::System.String value);
        partial void OnCellPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACBLNumber
        {
            get
            {
                return _ACBLNumber;
            }
            set
            {
                OnACBLNumberChanging(value);
                ReportPropertyChanging("ACBLNumber");
                _ACBLNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACBLNumber");
                OnACBLNumberChanged();
            }
        }
        private global::System.String _ACBLNumber;
        partial void OnACBLNumberChanging(global::System.String value);
        partial void OnACBLNumberChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BridgeMail", "GroupMail_GroupsGoupMail_Person", "GroupMail_Groups")]
        public EntityCollection<GroupMail_Groups> Lists
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGoupMail_Person", "GroupMail_Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGoupMail_Person", "GroupMail_Groups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BridgeMail", Name="GroupMail_Groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GroupMail_Groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GroupMail_Groups object.
        /// </summary>
        /// <param name="itemID">Initial value of the ItemID property.</param>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdByUser">Initial value of the CreatedByUser property.</param>
        /// <param name="groupName">Initial value of the GroupName property.</param>
        public static GroupMail_Groups CreateGroupMail_Groups(global::System.Int32 itemID, global::System.Int32 moduleID, global::System.DateTime createdDate, global::System.Int32 createdByUser, global::System.String groupName)
        {
            GroupMail_Groups groupMail_Groups = new GroupMail_Groups();
            groupMail_Groups.ItemID = itemID;
            groupMail_Groups.ModuleID = moduleID;
            groupMail_Groups.CreatedDate = createdDate;
            groupMail_Groups.CreatedByUser = createdByUser;
            groupMail_Groups.GroupName = groupName;
            return groupMail_Groups;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItemID
        {
            get
            {
                return _ItemID;
            }
            set
            {
                if (_ItemID != value)
                {
                    OnItemIDChanging(value);
                    ReportPropertyChanging("ItemID");
                    _ItemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ItemID");
                    OnItemIDChanged();
                }
            }
        }
        private global::System.Int32 _ItemID;
        partial void OnItemIDChanging(global::System.Int32 value);
        partial void OnItemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedByUser
        {
            get
            {
                return _CreatedByUser;
            }
            set
            {
                OnCreatedByUserChanging(value);
                ReportPropertyChanging("CreatedByUser");
                _CreatedByUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByUser");
                OnCreatedByUserChanged();
            }
        }
        private global::System.Int32 _CreatedByUser;
        partial void OnCreatedByUserChanging(global::System.Int32 value);
        partial void OnCreatedByUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BridgeMail", "GroupMail_GroupsGoupMail_Person", "GoupMail_Person")]
        public EntityCollection<GoupMail_Person> People
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GoupMail_Person>("BridgeMail.GroupMail_GroupsGoupMail_Person", "GoupMail_Person");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GoupMail_Person>("BridgeMail.GroupMail_GroupsGoupMail_Person", "GoupMail_Person", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BridgeMail", "GroupMail_GroupsGroupMail_History", "GroupMail_History")]
        public EntityCollection<GroupMail_History> Emails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<GroupMail_History>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_History");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<GroupMail_History>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_History", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BridgeMail", Name="GroupMail_History")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class GroupMail_History : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new GroupMail_History object.
        /// </summary>
        /// <param name="itemID">Initial value of the itemID property.</param>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdByUser">Initial value of the CreatedByUser property.</param>
        /// <param name="groupID">Initial value of the GroupID property.</param>
        /// <param name="groupMail_GroupsItemID">Initial value of the GroupMail_GroupsItemID property.</param>
        public static GroupMail_History CreateGroupMail_History(global::System.Int32 itemID, global::System.Int32 moduleID, global::System.DateTime createdDate, global::System.Int32 createdByUser, global::System.Int32 groupID, global::System.Int32 groupMail_GroupsItemID)
        {
            GroupMail_History groupMail_History = new GroupMail_History();
            groupMail_History.itemID = itemID;
            groupMail_History.ModuleID = moduleID;
            groupMail_History.CreatedDate = createdDate;
            groupMail_History.CreatedByUser = createdByUser;
            groupMail_History.GroupID = groupID;
            groupMail_History.GroupMail_GroupsItemID = groupMail_GroupsItemID;
            return groupMail_History;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 itemID
        {
            get
            {
                return _itemID;
            }
            set
            {
                if (_itemID != value)
                {
                    OnitemIDChanging(value);
                    ReportPropertyChanging("itemID");
                    _itemID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("itemID");
                    OnitemIDChanged();
                }
            }
        }
        private global::System.Int32 _itemID;
        partial void OnitemIDChanging(global::System.Int32 value);
        partial void OnitemIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CreatedByUser
        {
            get
            {
                return _CreatedByUser;
            }
            set
            {
                OnCreatedByUserChanging(value);
                ReportPropertyChanging("CreatedByUser");
                _CreatedByUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedByUser");
                OnCreatedByUserChanged();
            }
        }
        private global::System.Int32 _CreatedByUser;
        partial void OnCreatedByUserChanging(global::System.Int32 value);
        partial void OnCreatedByUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SentTo
        {
            get
            {
                return _SentTo;
            }
            set
            {
                OnSentToChanging(value);
                ReportPropertyChanging("SentTo");
                _SentTo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SentTo");
                OnSentToChanged();
            }
        }
        private global::System.String _SentTo;
        partial void OnSentToChanging(global::System.String value);
        partial void OnSentToChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupMail_GroupsItemID
        {
            get
            {
                return _GroupMail_GroupsItemID;
            }
            set
            {
                OnGroupMail_GroupsItemIDChanging(value);
                ReportPropertyChanging("GroupMail_GroupsItemID");
                _GroupMail_GroupsItemID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupMail_GroupsItemID");
                OnGroupMail_GroupsItemIDChanged();
            }
        }
        private global::System.Int32 _GroupMail_GroupsItemID;
        partial void OnGroupMail_GroupsItemIDChanging(global::System.Int32 value);
        partial void OnGroupMail_GroupsItemIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BridgeMail", "GroupMail_GroupsGroupMail_History", "GroupMail_Groups")]
        public GroupMail_Groups List
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_Groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_Groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<GroupMail_Groups> ListReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_Groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<GroupMail_Groups>("BridgeMail.GroupMail_GroupsGroupMail_History", "GroupMail_Groups", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
